#!/bin/sh
### BEGIN INIT INFO
# Provides:          springfield
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start player at boot time
# Description:       Doh.
### END INIT INFO

NBOX_LOCATION=$(sudo blkid | grep "NBOX" | cut -d':' -f 1)
if [ $NBOX_LOCATION ]; then pmount $NBOX_LOCATION; else echo "NBOX_LOCATION: Please insert USB and reboot"; fi
